version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      diggers:
        aliases:
          - nikolka.diggers

networks:
  diggers:
    external: true
